CPPCORE_DOC_DIR     = $(CPPCORE_TOP)/doc
CPPCORE_ARCH_DIR    = $(CPPCORE_TOP)/arch
CPPCORE_DRIVERS_DIR = $(CPPCORE_TOP)/drivers
CPPCORE_INCLUDE_DIR = $(CPPCORE_TOP)/include

#CPPCORE_SRC_DIRS    = $(CPPCORE_ARCH_DIR)/$(CPPCORE_ARCH)
#CPPCORE_SRC         = $(wildcard $(addsuffix /*.cpp, $(CPPCORE_SRC_DIRS)))

CPPCORE_INCLUDE     = -I $(CPPCORE_INCLUDE_DIR)
CPPCORE_INCLUDE    += -I $(CPPCORE_DRIVERS_DIR)
CPPCORE_INCLUDE    += -I $(CPPCORE_ARCH_DIR)/$(CPPCORE_ARCH)/include
